CREATE DATABASE SITUACIONALUMNO;

CREATE TABLE CARRERA (
    ID_CARRERA INT PRIMARY KEY AUTO_INCREMENT,                    
    NOMBRE VARCHAR(100)
);

CREATE TABLE MATERIA (
    ID_MATERIA INT PRIMARY KEY AUTO_INCREMENT,                    
    NOMBRE VARCHAR(100),
	TIPO VARCHAR(30),
	ID_CARRERA INT,
	FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA) ON DELETE CASCADE
);

CREATE TABLE MATERIA_CORRELATIVIDAD (
	ID_CORRELATIVIDAD_MATERIA INT PRIMARY KEY AUTO_INCREMENT,
	ID_CARRERA INT,
	ID_MATERIA INT,
	ID_MATERIA_CORRELATIVA INT,
	FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA) ON DELETE CASCADE,
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID_MATERIA) ON DELETE CASCADE,
    FOREIGN KEY (ID_MATERIA_CORRELATIVA) REFERENCES MATERIA(ID_MATERIA) ON DELETE CASCADE
);

CREATE TABLE ALUMNO (
    DNI INT PRIMARY KEY,                    
    NOMBRE VARCHAR(100),
	APELLIDO VARCHAR(100),
	TELEFONO VARCHAR(50),
	MAIL VARCHAR(100),
	ID_CARRERA INT,
	FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA) ON DELETE CASCADE
);

CREATE TABLE CONDICION_ALUMNO_MATERIA (
	ID_CONDICION_ALUMNO_MATERIA INT PRIMARY KEY AUTO_INCREMENT,
	DNI INT,
	ID_CARRERA INT,
	ID_MATERIA INT,
	SITUACION VARCHAR(50) DEFAULT 'NO CURSO',
	FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA) ON DELETE CASCADE,
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID_MATERIA) ON DELETE CASCADE,
    FOREIGN KEY (DNI) REFERENCES ALUMNO(DNI) ON DELETE CASCADE
);

 